# FEATURE TRANSFORMATION

In [8]:
import numpy as np
import pandas as pd

In [10]:
data=pd.read_csv('TITANICDW.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
data=pd.read_csv('TITANICDW.csv',usecols=['Fare'])
data.head()

      Fare
0   7.2500
1  71.2833
2   7.9250
3  53.1000
4   8.0500

In [12]:
data['Fare'].skew()

4.787316519674893

# Log Transformation

In [16]:
data['Log_Fare']=np.log(data['Fare']+0.0001)
data['Log_Fare'].skew()

-4.575600082722933

# Root Transformation

In [19]:
data['sqr_Fare']=data['Fare']**(1/4.7)
data['sqr_Fare'].skew()

0.00982006067812734

# Reciprocal Transformation

In [22]:
data['Rec_Fare']=1/(data['Fare']+0.01)
data['Rec_Fare'].skew()

7.523650082079874

# BoxCox

In [25]:
from scipy.stats import boxcox

In [28]:
#Transform training data & save lambda value
data['Fare_boxcox'], param=boxcox(data.Fare+0.01)

In [29]:
print("lambda =",param)

lambda = 0.18091321955494596

In [30]:
data['Fare_boxcox'].skew()

0.25282461235568676