# Discretization

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("strokeprediction.csv")
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,30669,Male,3.0,0,0,No,children,Rural,95.12,18.0,NaN,0
1,30468,Male,58.0,1,0,Yes,Private,Urban,87.96,39.2,never smoked,0
2,16523,Female,8.0,0,0,No,Private,Urban,110.89,17.6,NaN,0
3,56543,Female,70.0,0,0,Yes,Private,Rural,69.04,35.9,formerly smoked,0
4,46136,Male,14.0,0,0,No,Never_worked,Rural,161.28,19.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
43395,56196,Female,10.0,0,0,No,children,Urban,58.64,20.4,never smoked,0
43396,5450,Female,56.0,0,0,Yes,Govt_job,Urban,213.61,55.4,formerly smoked,0
43397,28375,Female,82.0,1,0,Yes,Private,Urban,91.94,28.9,formerly smoked,0
43398,27973,Male,40.0,0,0,Yes,Private,Urban,99.16,33.2,never smoked,0
43399,36271,Female,82.0,0,0,Yes,Private,Urban,79.48,20.6,never smoked,0

In [6]:
df.shape

(43400, 12)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43400 entries, 0 to 43399
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 43400 non-null  int64
 1   gender             43400 non-null  object
 2   age                43400 non-null  float64
 3   hypertension       43400 non-null  int64
 4   heart_disease      43400 non-null  int64
 5   ever_married       43400 non-null  object
 6   work_type          43400 non-null  object
 7   Residence_type     43400 non-null  object
 8   avg_glucose_level  43400 non-null  float64
 9   bmi                41938 non-null  float64
 10  smoking_status     30108 non-null  object
 11  stroke             43400 non-null  int64
dtypes: float64(3), int64(4), object(5)
memory usage: 4.0+ MB

In [9]:
df["stroke"].value_counts()

0    42617
1      783
Name: stroke, dtype: int64

# Creating Bins

In [11]:
intervals=[0,12,19,30,60,90]
categories=['child','teenager','young_adult','middle_aged','senior_citizen']

# Discretization

In [13]:
df['age_category']=pd.cut(df['age'],bins=intervals,labels=categories)

In [14]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,age_category
0,30669,Male,3.0,0,0,No,children,Rural,95.12,18.0,NaN,0,child
1,30468,Male,58.0,1,0,Yes,Private,Urban,87.96,39.2,never smoked,0,middle_aged
2,16523,Female,8.0,0,0,No,Private,Urban,110.89,17.6,NaN,0,child
3,56543,Female,70.0,0,0,Yes,Private,Rural,69.04,35.9,formerly smoked,0,senior_citizen
4,46136,Male,14.0,0,0,No,Never_worked,Rural,161.28,19.1,NaN,0,teenager

In [16]:
df[['age','age_category']]

        age    age_category
0       3.0           child
1      58.0     middle_aged
2       8.0           child
3      70.0  senior_citizen
4      14.0        teenager
...     ...             ...
43395  10.0           child
43396  56.0     middle_aged
43397  82.0  senior_citizen
43398  40.0     middle_aged
43399  82.0  senior_citizen

[43400 rows x 2 columns]

In [18]:
df['age_category'].value_counts()

middle_aged       18653
senior_citizen    10511
young_adult        5725
child              5326
teenager           3185
Name: age_category, dtype: int64

In [19]:
pd.crosstab(df.stroke,df.age_category)

age_category  child  teenager  young_adult  middle_aged  senior_citizen
stroke
0              5325      3184         5723        18453            9932
1                 1         1            2          200             579